### ISSUE TITLE
Minimal readme

### ISSUE THREAD

**Issue by hlbstd** [manekinekko/dojo-doh-junit-report#1]
Could you please add some information to the readme so that Dojo noobs (like me) can use this ?
I can't get it running and for now I can't tell if it's a bug or only me being very stupid.

**Comment by manekinekko** [comment]
Hi @traken I update the readme file. Please tell me if this is Ok for you? Keep also in mind that this script still need a lot of improvements, so feel free submit your changes ^^

**Comment by hlbstd** [comment]
Hi @manekinekko , thank you for updating the readme. If by " load it from the normal runner" you mean make the test runner depend from junit-runner.js instead of the default runner.js this is what I have been trying to do.
Doesn't work for me either with Rhino or in a browser.

Here is what I have been trying to do:
My test module:

``` javascript
define(["doh/runner-junit", "my/sources/toBeTested"], function(doh,toBeTested)
```

I am getting this message error with Rhino:
`js: "<eval'ed string>#1(Function)#1(eval)", line 7: uncaught JavaScript runtime exception: ReferenceError: "window" is undefined`

And when trying to run it from a browser:
`TypeError: node is null 
    return nlsModule && nlsModule.executed && nlsModule.result;    dojo.js (line 778)`

My test works with both methods when I run It with the default runner.js . Also, please note that I am working under Dojo 1.7.5.

Please tell me if I'm doing anything wrong.I am for now in a learning phase (both for Dojo and JS), but I would be glad to help improve this script in the future as it is important for me (the lack of junit compliant report is kind of a blocker when trying to reuse DOH results output...).

**Comment by manekinekko** [comment]
Hi @traken sorry for being absent all this time. I tried to fix this issue. Please see commit (89c85dae49d02c8427e99bae4affdae8ea8411a6) and tell me if this is OK for you.

thx.

**Comment by manekinekko** [comment]
I
